# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(829, 929)
        Form.setMinimumSize(QtCore.QSize(829, 929))
        Form.setMaximumSize(QtCore.QSize(829, 929))
        self.Ori_image_View = QtWidgets.QGraphicsView(Form)
        self.Ori_image_View.setGeometry(QtCore.QRect(10, 10, 401, 401))
        self.Ori_image_View.setObjectName("Ori_image_View")

        self.Styled_image_View = QtWidgets.QGraphicsView(Form)
        self.Styled_image_View.setGeometry(QtCore.QRect(10, 420, 401, 401))
        self.Styled_image_View.setObjectName("Styled_image_View")

        self.Ori_image_Label = QtWidgets.QLabel(Form)
        self.Ori_image_Label.setGeometry(QtCore.QRect(420, 20, 161, 31))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)

        self.Ori_image_Label.setFont(font)
        self.Ori_image_Label.setObjectName("Ori_image_Label")
        self.Styled_image_Label = QtWidgets.QLabel(Form)
        self.Styled_image_Label.setGeometry(QtCore.QRect(420, 160, 151, 31))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)

        self.Styled_image_Label.setFont(font)
        self.Styled_image_Label.setObjectName("Styled_image_Label")

        self.File_Edit = QtWidgets.QTextEdit(Form)
        self.File_Edit.setGeometry(QtCore.QRect(420, 60, 261, 91))
        self.File_Edit.setObjectName("File_Edit")

        self.File_choose_Button = QtWidgets.QPushButton(Form)
        self.File_choose_Button.setGeometry(QtCore.QRect(590, 20, 91, 31))
        self.File_choose_Button.setObjectName("File_choose_Button")

        self.Save_Button = QtWidgets.QPushButton(Form)
        self.Save_Button.setGeometry(QtCore.QRect(600, 380, 81, 31))
        self.Save_Button.setObjectName("Save_Button")

        self.Start_Button = QtWidgets.QPushButton(Form)
        self.Start_Button.setGeometry(QtCore.QRect(420, 310, 261, 61))

        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)

        self.Start_Button.setFont(font)
        self.Start_Button.setObjectName("Start_Button")

        self.Schedule_Viewer = QtWidgets.QTextBrowser(Form)
        self.Schedule_Viewer.setGeometry(QtCore.QRect(10, 830, 811, 91))
        self.Schedule_Viewer.setObjectName("Schedule_Viewer")

        self.Schedule_Label = QtWidgets.QLabel(Form)
        self.Schedule_Label.setGeometry(QtCore.QRect(940, 600, 101, 20))

        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)

        self.Schedule_Label.setFont(font)
        self.Schedule_Label.setObjectName("Schedule_Label")

        self.File_Edit_style = QtWidgets.QTextEdit(Form)
        self.File_Edit_style.setGeometry(QtCore.QRect(420, 200, 261, 101))
        self.File_Edit_style.setObjectName("File_Edit_style")

        self.File_choose_Button_2 = QtWidgets.QPushButton(Form)
        self.File_choose_Button_2.setGeometry(QtCore.QRect(590, 160, 91, 31))
        self.File_choose_Button_2.setObjectName("File_choose_Button_2")

        self.Converted_image_View = QtWidgets.QGraphicsView(Form)
        self.Converted_image_View.setGeometry(QtCore.QRect(420, 420, 401, 401))
        self.Converted_image_View.setObjectName("Converted_image_View")

        self.Styled_image_Label_2 = QtWidgets.QLabel(Form)
        self.Styled_image_Label_2.setGeometry(QtCore.QRect(420, 390, 151, 31))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)

        self.Styled_image_Label_2.setFont(font)
        self.Styled_image_Label_2.setObjectName("Styled_image_Label_2")

        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(700, 20, 121, 391))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        sys.stdout = EmittingStream(textWritten = self.outputWritten)
        sys.stderr = EmittingStream(textWritten = self.outputWritten)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Style transfer"))
        self.Ori_image_Label.setText(_translate("Form", "Original image"))
        self.Styled_image_Label.setText(_translate("Form", "Styled image"))
        self.File_choose_Button.setText(_translate("Form", "Choose"))
        self.Save_Button.setText(_translate("Form", "Save"))
        self.Start_Button.setText(_translate("Form", "Start"))
        self.Schedule_Label.setText(_translate("Form", "Schedule"))
        self.File_choose_Button_2.setText(_translate("Form", "Choose"))
        self.Styled_image_Label_2.setText(_translate("Form", "Result image"))
    
    def outputWritten(self,text):
        cursor = self.Schedule_Viewer.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)

        cursor.insertText(text)

        self.Schedule_Viewer.setTextCursor(cursor)
        self.Schedule_Viewer.ensureCursorVisible()

class EmittingStream(QtCore.QObject):
    textWritten = QtCore.pyqtSignal(str)

    def write(self,text):
        self.textWritten.emit(str(text))
